spring.application.name=demo

# URL kết nối: jdbc:mysql://[host]:[port]/[tên_db]
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/demodb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# Tài khoản đăng nhập DB
spring.datasource.username=root
# Mật khẩu đăng nhập DB
spring.datasource.password=01269258179
# Driver Class Name của MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update